import type { ButtonObject, Page, ShapeObject, ShirtView, TemplateDef, TextObject } from "../types";
import { uuid } from "../lib/ids";

function text(
  partial: Pick<TextObject, "x" | "y" | "width" | "text"> & Partial<Omit<TextObject, "id" | "type">>,
): TextObject {
  return {
    id: uuid(),
    type: "text",
    x: partial.x,
    y: partial.y,
    width: partial.width,
    text: partial.text,
    rotation: partial.rotation ?? 0,
    opacity: partial.opacity ?? 1,
    fontWeight: partial.fontWeight ?? 400,
    fontFamily: partial.fontFamily ?? "Inter",
    align: partial.align ?? "left",
    fill: partial.fill ?? "#1a1614",
    fontSize: partial.fontSize ?? 24,
  };
}

function shape(
  partial: Omit<ShapeObject, "id" | "type" | "rotation" | "opacity" | "stroke" | "strokeWidth" | "cornerRadius"> &
    Partial<ShapeObject>,
): ShapeObject {
  return {
    id: uuid(),
    type: "shape",
    rotation: 0,
    opacity: 1,
    stroke: "transparent",
    strokeWidth: 0,
    cornerRadius: 0,
    ...partial,
  };
}

const INK = "#1a1614";
const PAPER = "#f6f1e8";
const OXBLOOD = "#7a2e2e";
const GOLD = "#c4a574";
const NAVY = "#1e2d3d";
const FOREST = "#2f4a3c";
const CREAM = "#fbf7f0";
const TERRACOTTA = "#c45c26";

function button(
  partial: Pick<ButtonObject, "x" | "y" | "width" | "height" | "text" | "href"> & Partial<ButtonObject>,
): ButtonObject {
  return {
    id: uuid(),
    type: "button",
    rotation: 0,
    opacity: 1,
    fill: OXBLOOD,
    textFill: PAPER,
    fontFamily: "Inter",
    fontSize: 22,
    fontWeight: 600,
    cornerRadius: 8,
    ...partial,
  };
}

function page(background: string, objects: Page["objects"], role?: ShirtView): Page {
  return { id: uuid(), background, objects, ...(role ? { role } : {}) };
}

export const TEMPLATES: TemplateDef[] = [
  {
    id: "midnight-quote",
    name: "Midnight quote",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page(INK, [
        shape({ shape: "rect", x: 72, y: 72, width: 10, height: 936, fill: GOLD }),
        text({
          x: 120,
          y: 280,
          width: 860,
          text: "Design like you mean it.",
          fontFamily: "Playfair Display",
          fontSize: 72,
          fontWeight: 600,
          align: "left",
          fill: PAPER,
        }),
        text({
          x: 120,
          y: 860,
          width: 860,
          text: "A quiet mark. A lasting one.",
          fontFamily: "Inter",
          fontSize: 24,
          fontWeight: 400,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "launch-story",
    name: "Launch story",
    category: "social",
    width: 1080,
    height: 1920,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 1080, height: 720, fill: OXBLOOD }),
        text({
          x: 80,
          y: 220,
          width: 920,
          text: "NOW OPEN",
          fontFamily: "Oswald",
          fontSize: 96,
          fontWeight: 600,
          align: "left",
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 360,
          width: 920,
          text: "The spring collection",
          fontFamily: "Playfair Display",
          fontSize: 42,
          fontWeight: 500,
          fill: GOLD,
        }),
        text({
          x: 80,
          y: 880,
          width: 920,
          text: "Saturday 10–4\nHarbor & Vine",
          fontFamily: "Inter",
          fontSize: 36,
          fontWeight: 500,
          fill: INK,
        }),
        text({
          x: 80,
          y: 1720,
          width: 920,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 22,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
      ]),
    ],
  },
  {
    id: "thumbnail-hook",
    name: "Thumbnail hook",
    category: "social",
    width: 1280,
    height: 720,
    build: () => [
      page(NAVY, [
        shape({ shape: "rect", x: 0, y: 0, width: 18, height: 720, fill: GOLD }),
        text({
          x: 80,
          y: 180,
          width: 1120,
          text: "STOP SCROLLING.",
          fontFamily: "Oswald",
          fontSize: 92,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 320,
          width: 1120,
          text: "Three layouts that actually ship.",
          fontFamily: "Inter",
          fontSize: 36,
          fontWeight: 400,
          fill: GOLD,
        }),
        shape({ shape: "rect", x: 80, y: 560, width: 220, height: 64, fill: OXBLOOD, cornerRadius: 4 }),
        text({
          x: 80,
          y: 572,
          width: 220,
          text: "WATCH",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 600,
          align: "center",
          fill: PAPER,
        }),
      ]),
    ],
  },
  {
    id: "event-banner",
    name: "Event banner",
    category: "social",
    width: 1200,
    height: 630,
    build: () => [
      page(CREAM, [
        shape({ shape: "rect", x: 0, y: 0, width: 420, height: 630, fill: FOREST }),
        text({
          x: 48,
          y: 80,
          width: 324,
          text: "FRI\nJUN 12",
          fontFamily: "Oswald",
          fontSize: 64,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 48,
          y: 500,
          width: 324,
          text: "Doors 7pm",
          fontFamily: "Inter",
          fontSize: 22,
          fill: GOLD,
        }),
        text({
          x: 500,
          y: 160,
          width: 640,
          text: "Evening talk",
          fontFamily: "Inter",
          fontSize: 24,
          fontWeight: 500,
          fill: FOREST,
        }),
        text({
          x: 500,
          y: 210,
          width: 640,
          text: "Paper, type,\nand the quiet mark.",
          fontFamily: "Playfair Display",
          fontSize: 52,
          fontWeight: 600,
          fill: INK,
        }),
      ]),
    ],
  },
  {
    id: "brief-announcement",
    name: "Brief announcement",
    category: "social",
    width: 1600,
    height: 900,
    build: () => [
      page(INK, [
        shape({ shape: "ellipse", x: 1180, y: -120, width: 560, height: 560, fill: OXBLOOD }),
        text({
          x: 80,
          y: 280,
          width: 1100,
          text: "We shipped v1.",
          fontFamily: "Playfair Display",
          fontSize: 88,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 420,
          width: 1000,
          text: "A free design studio that lives on your machine. No account. No feed.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "keynote-title",
    name: "Keynote title",
    category: "presentation",
    width: 1920,
    height: 1080,
    build: () => [
      page(NAVY, [
        shape({ shape: "rect", x: 160, y: 520, width: 160, height: 6, fill: GOLD }),
        text({
          x: 160,
          y: 280,
          width: 1600,
          text: "The imprint you leave",
          fontFamily: "Playfair Display",
          fontSize: 88,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 160,
          y: 560,
          width: 1400,
          text: "On type, paper, and making things that last the week.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "keynote-deck",
    name: "Keynote deck",
    category: "presentation",
    width: 1920,
    height: 1080,
    build: () => [
      page(NAVY, [
        shape({ shape: "rect", x: 160, y: 520, width: 160, height: 6, fill: GOLD }),
        text({
          x: 160,
          y: 300,
          width: 1600,
          text: "Three rules for layouts",
          fontFamily: "Playfair Display",
          fontSize: 80,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 160,
          y: 560,
          width: 1400,
          text: "A short deck you can actually present.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: GOLD,
        }),
      ]),
      page(CREAM, [
        text({
          x: 160,
          y: 120,
          width: 1600,
          text: "01  —  Hierarchy",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
        text({
          x: 160,
          y: 220,
          width: 1600,
          text: "One idea, larger than the rest.",
          fontFamily: "Playfair Display",
          fontSize: 64,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 160,
          y: 420,
          width: 1200,
          text: "If everything shouts, nothing is heard. Pick a headline, a supporting line, and let the rest of the page breathe.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: "#3f3833",
        }),
      ]),
      page(FOREST, [
        text({
          x: 160,
          y: 200,
          width: 1600,
          text: "Thank you",
          fontFamily: "Playfair Display",
          fontSize: 88,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 160,
          y: 360,
          width: 1400,
          text: "Questions, margins, and coffee after.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "market-day",
    name: "Market day",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page(TERRACOTTA, [
        shape({ shape: "rect", x: 64, y: 64, width: 952, height: 952, fill: "transparent", stroke: PAPER, strokeWidth: 3 }),
        text({
          x: 100,
          y: 180,
          width: 880,
          text: "50% OFF",
          fontFamily: "Oswald",
          fontSize: 120,
          fontWeight: 600,
          align: "center",
          fill: PAPER,
        }),
        text({
          x: 100,
          y: 360,
          width: 880,
          text: "Weekend market",
          fontFamily: "Playfair Display",
          fontSize: 48,
          fontWeight: 500,
          align: "center",
          fill: CREAM,
        }),
        text({
          x: 100,
          y: 820,
          width: 880,
          text: "Sat–Sun  ·  9 until sold out",
          fontFamily: "Inter",
          fontSize: 24,
          align: "center",
          fill: PAPER,
        }),
      ]),
    ],
  },
  {
    id: "workshop-poster",
    name: "Workshop poster",
    category: "print",
    width: 794,
    height: 1123,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 794, height: 280, fill: INK }),
        text({
          x: 48,
          y: 72,
          width: 698,
          text: "WORKSHOP",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          fill: GOLD,
        }),
        text({
          x: 48,
          y: 120,
          width: 698,
          text: "Letterpress\nfor beginners",
          fontFamily: "Playfair Display",
          fontSize: 52,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 48,
          y: 360,
          width: 698,
          text: "A Saturday in the studio: paper, ink, and a press that still smells like 1924.",
          fontFamily: "Inter",
          fontSize: 24,
          fill: INK,
        }),
        shape({ shape: "rect", x: 48, y: 520, width: 698, height: 2, fill: GOLD }),
        text({
          x: 48,
          y: 560,
          width: 698,
          text: "12 April  ·  10:00–16:00\nThe Bindery, Oak Street",
          fontFamily: "Inter",
          fontSize: 24,
          fontWeight: 500,
          fill: INK,
        }),
        text({
          x: 48,
          y: 1020,
          width: 698,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 18,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
      ]),
    ],
  },
  {
    id: "letter-flyer",
    name: "Letter flyer",
    category: "print",
    width: 816,
    height: 1056,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 816, height: 40, fill: OXBLOOD }),
        shape({ shape: "rect", x: 0, y: 1016, width: 816, height: 40, fill: INK }),
        text({
          x: 64,
          y: 88,
          width: 688,
          text: "OPEN STUDIO",
          fontFamily: "Oswald",
          fontSize: 22,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
        text({
          x: 64,
          y: 136,
          width: 688,
          text: "Paper & press",
          fontFamily: "Playfair Display",
          fontSize: 64,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 64,
          y: 248,
          width: 688,
          text: "A Saturday open house. Prints, type, and coffee in the bindery.",
          fontFamily: "Inter",
          fontSize: 22,
          fill: INK,
        }),
        shape({ shape: "rect", x: 64, y: 360, width: 120, height: 4, fill: GOLD }),
        text({
          x: 64,
          y: 400,
          width: 688,
          text: "18 October  ·  11:00–16:00\nOak Street Bindery",
          fontFamily: "Inter",
          fontSize: 22,
          fontWeight: 500,
          fill: INK,
        }),
        text({
          x: 64,
          y: 1024,
          width: 688,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 16,
          fontWeight: 500,
          fill: PAPER,
        }),
      ]),
    ],
  },
  {
    id: "band-tee",
    name: "Band tee",
    category: "print",
    width: 1200,
    height: 1600,
    build: () => [
      page(
        INK,
        [
        shape({
          shape: "rect",
          x: 72,
          y: 72,
          width: 1056,
          height: 1456,
          fill: "transparent",
          stroke: GOLD,
          strokeWidth: 2,
        }),
        text({
          x: 100,
          y: 200,
          width: 1000,
          text: "WORLD TOUR",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          align: "center",
          fill: GOLD,
          letterSpacing: 12,
        }),
        text({
          x: 80,
          y: 380,
          width: 1040,
          text: "LAST",
          fontFamily: "Anton",
          fontSize: 168,
          fontWeight: 400,
          align: "center",
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 560,
          width: 1040,
          text: "LIGHT",
          fontFamily: "Bebas Neue",
          fontSize: 188,
          fontWeight: 400,
          align: "center",
          fill: PAPER,
        }),
        shape({ shape: "rect", x: 520, y: 800, width: 160, height: 4, fill: OXBLOOD }),
        text({
          x: 100,
          y: 860,
          width: 1000,
          text: "HARBOR  ·  VINE  ·  OAK",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          align: "center",
          fill: GOLD,
        }),
        text({
          x: 100,
          y: 1380,
          width: 1000,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 20,
          fontWeight: 500,
          align: "center",
          fill: OXBLOOD,
          letterSpacing: 8,
        }),
      ],
        "front",
      ),
    ],
  },
  {
    id: "studio-mark",
    name: "Studio mark",
    category: "print",
    width: 1200,
    height: 1600,
    build: () => [
      page(
        CREAM,
        [
        text({
          x: 200,
          y: 720,
          width: 800,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 42,
          fontWeight: 500,
          align: "center",
          fill: INK,
          letterSpacing: 14,
        }),
        shape({ shape: "rect", x: 560, y: 792, width: 80, height: 2, fill: GOLD }),
        text({
          x: 200,
          y: 820,
          width: 800,
          text: "OAK STREET",
          fontFamily: "Inter",
          fontSize: 16,
          fontWeight: 400,
          align: "center",
          fill: "#6b645c",
          letterSpacing: 6,
        }),
      ],
        "front",
      ),
    ],
  },
  {
    id: "session-cover",
    name: "Session cover",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page(FOREST, [
        shape({ shape: "ellipse", x: 620, y: 620, width: 640, height: 640, fill: "#263d32" }),
        text({
          x: 80,
          y: 120,
          width: 920,
          text: "EPISODE 12",
          fontFamily: "Oswald",
          fontSize: 24,
          fontWeight: 500,
          fill: GOLD,
        }),
        text({
          x: 80,
          y: 200,
          width: 900,
          text: "Margins\n& meaning",
          fontFamily: "Playfair Display",
          fontSize: 80,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 900,
          width: 900,
          text: "A conversation with the bindery",
          fontFamily: "Inter",
          fontSize: 24,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "menu-story",
    name: "Menu story",
    category: "social",
    width: 1080,
    height: 1920,
    build: () => [
      page(CREAM, [
        text({
          x: 80,
          y: 160,
          width: 920,
          text: "TONIGHT",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          align: "center",
          fill: OXBLOOD,
        }),
        text({
          x: 80,
          y: 220,
          width: 920,
          text: "Supper menu",
          fontFamily: "Playfair Display",
          fontSize: 64,
          fontWeight: 600,
          align: "center",
          fill: INK,
        }),
        shape({ shape: "rect", x: 490, y: 330, width: 100, height: 3, fill: GOLD }),
        text({
          x: 100,
          y: 420,
          width: 880,
          text: "Celeriac soup\nGrilled mackerel\nBrown butter tart",
          fontFamily: "Inter",
          fontSize: 36,
          fontWeight: 400,
          align: "center",
          fill: INK,
        }),
        text({
          x: 80,
          y: 1720,
          width: 920,
          text: "Seatings at 6 and 8",
          fontFamily: "Inter",
          fontSize: 22,
          align: "center",
          fill: "#6b645c",
        }),
      ]),
    ],
  },
  {
    id: "case-study",
    name: "Case study",
    category: "presentation",
    width: 1920,
    height: 1080,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 640, height: 1080, fill: INK }),
        text({
          x: 64,
          y: 120,
          width: 512,
          text: "CASE 04",
          fontFamily: "Oswald",
          fontSize: 24,
          fontWeight: 500,
          fill: GOLD,
        }),
        text({
          x: 64,
          y: 200,
          width: 512,
          text: "The Harbor press",
          fontFamily: "Playfair Display",
          fontSize: 56,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 760,
          y: 200,
          width: 1040,
          text: "A studio identity that could be stamped, not just screened.",
          fontFamily: "Playfair Display",
          fontSize: 44,
          fontWeight: 500,
          fill: INK,
        }),
        text({
          x: 760,
          y: 420,
          width: 1000,
          text: "We kept the mark small, the paper warm, and the type a little too serious. It held.",
          fontFamily: "Inter",
          fontSize: 28,
          fill: "#3f3833",
        }),
      ]),
    ],
  },
  {
    id: "simple-site",
    name: "Simple site",
    category: "site",
    width: 1440,
    height: 900,
    build: () => [
      page(CREAM, [
        shape({ shape: "rect", x: 0, y: 0, width: 1440, height: 72, fill: INK }),
        text({
          x: 48,
          y: 22,
          width: 240,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 22,
          fontWeight: 500,
          fill: PAPER,
        }),
        button({
          x: 1180,
          y: 16,
          width: 212,
          height: 40,
          text: "Get in touch",
          href: "#page-2",
          fontSize: 16,
          cornerRadius: 6,
        }),
        text({
          x: 80,
          y: 220,
          width: 820,
          text: "A small site,\nmade by you.",
          fontFamily: "Playfair Display",
          fontSize: 72,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 80,
          y: 420,
          width: 640,
          text: "Add buttons that open a web address or jump to another page. Then export as Webpage (HTML).",
          fontFamily: "Inter",
          fontSize: 22,
          fill: "#3f3833",
        }),
        button({
          x: 80,
          y: 540,
          width: 220,
          height: 56,
          text: "Visit a link",
          href: "https://example.com",
        }),
        button({
          x: 320,
          y: 540,
          width: 220,
          height: 56,
          text: "Next page",
          href: "#page-2",
          fill: INK,
        }),
      ]),
      page(INK, [
        text({
          x: 80,
          y: 240,
          width: 900,
          text: "Hello.",
          fontFamily: "Playfair Display",
          fontSize: 80,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 80,
          y: 360,
          width: 720,
          text: "This second page is just another canvas. Buttons can jump here with “Goes to → This site’s page 2”.",
          fontFamily: "Inter",
          fontSize: 24,
          fill: GOLD,
        }),
        button({
          x: 80,
          y: 520,
          width: 200,
          height: 52,
          text: "Back home",
          href: "#page-1",
          fill: PAPER,
          textFill: INK,
        }),
      ]),
    ],
  },
  {
    id: "wide-landing",
    name: "Wide landing",
    category: "site",
    width: 1920,
    height: 1200,
    build: () => [
      page(NAVY, [
        text({
          x: 120,
          y: 280,
          width: 980,
          text: "Open the shop",
          fontFamily: "Playfair Display",
          fontSize: 88,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 120,
          y: 420,
          width: 720,
          text: "One page. One button. Put your website address on it.",
          fontFamily: "Inter",
          fontSize: 28,
          fill: GOLD,
        }),
        button({
          x: 120,
          y: 540,
          width: 260,
          height: 64,
          text: "Shop now",
          href: "https://example.com",
          fill: GOLD,
          textFill: INK,
        }),
      ]),
    ],
  },
  {
    id: "studio-note",
    name: "Studio note",
    category: "email",
    width: 600,
    height: 800,
    build: () => [
      page(CREAM, [
        shape({ shape: "rect", x: 0, y: 0, width: 600, height: 72, fill: INK }),
        text({
          x: 32,
          y: 24,
          width: 240,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 20,
          fontWeight: 500,
          fill: PAPER,
        }),
        text({
          x: 36,
          y: 120,
          width: 528,
          text: "A note from the press.",
          fontFamily: "Playfair Display",
          fontSize: 42,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 36,
          y: 240,
          width: 528,
          text: "We printed the spring cards this week. Warm paper, a small mark, nothing extra. If you’d like a set, the button below opens the shop.",
          fontFamily: "Inter",
          fontSize: 18,
          fill: "#3f3833",
        }),
        button({
          x: 36,
          y: 400,
          width: 200,
          height: 48,
          text: "Visit the shop",
          href: "https://example.com",
          fontSize: 16,
          cornerRadius: 6,
        }),
        text({
          x: 36,
          y: 720,
          width: 528,
          text: "Sent with ink on paper.",
          fontFamily: "Inter",
          fontSize: 13,
          fill: "#6b645c",
        }),
      ]),
    ],
  },
  {
    id: "saturday-hours",
    name: "Saturday hours",
    category: "email",
    width: 600,
    height: 1200,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 600, height: 80, fill: OXBLOOD }),
        text({
          x: 36,
          y: 28,
          width: 280,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 22,
          fontWeight: 500,
          fill: PAPER,
        }),
        text({
          x: 36,
          y: 130,
          width: 528,
          text: "Come by Saturday.",
          fontFamily: "Playfair Display",
          fontSize: 48,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 36,
          y: 260,
          width: 528,
          text: "The studio is open 10–2. Proofs on the table, coffee on the press. Bring a note if you want something printed.",
          fontFamily: "Inter",
          fontSize: 20,
          fill: "#3f3833",
        }),
        button({
          x: 36,
          y: 430,
          width: 220,
          height: 52,
          text: "See the hours",
          href: "https://example.com",
          fontSize: 16,
          cornerRadius: 6,
        }),
        shape({ shape: "rect", x: 36, y: 540, width: 528, height: 1, fill: GOLD }),
        text({
          x: 36,
          y: 580,
          width: 528,
          text: "Can’t make it?",
          fontFamily: "Playfair Display",
          fontSize: 32,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 36,
          y: 640,
          width: 528,
          text: "Write us. The button opens their mail app.",
          fontFamily: "Inter",
          fontSize: 18,
          fill: "#3f3833",
        }),
        button({
          x: 36,
          y: 720,
          width: 200,
          height: 48,
          text: "Email us",
          href: "mailto:hello@studio.com",
          fill: INK,
          fontSize: 16,
          cornerRadius: 6,
        }),
        text({
          x: 36,
          y: 1100,
          width: 528,
          text: "Harbor & Vine · Saturday 10–2",
          fontFamily: "Inter",
          fontSize: 14,
          fill: "#6b645c",
        }),
      ]),
    ],
  },
  {
    id: "paper-talk",
    name: "Paper talk",
    category: "presentation",
    width: 1920,
    height: 1080,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 28, height: 1080, fill: OXBLOOD }),
        text({
          x: 120,
          y: 280,
          width: 1600,
          text: "What the room remembers",
          fontFamily: "Playfair Display",
          fontSize: 76,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 120,
          y: 420,
          width: 1200,
          text: "A short talk on paper, ink, and leaving the right mark.",
          fontFamily: "Inter",
          fontSize: 28,
          fill: "#3f3833",
        }),
        shape({ shape: "rect", x: 120, y: 900, width: 160, height: 8, fill: GOLD }),
      ]),
      page(OXBLOOD, [
        text({
          x: 120,
          y: 220,
          width: 1600,
          text: "01",
          fontFamily: "Oswald",
          fontSize: 28,
          fontWeight: 500,
          fill: GOLD,
        }),
        text({
          x: 120,
          y: 300,
          width: 1600,
          text: "Say one thing, then stop.",
          fontFamily: "Playfair Display",
          fontSize: 64,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 120,
          y: 460,
          width: 1100,
          text: "The rest is margin. Let the type sit on the page like a letter you meant to send.",
          fontFamily: "Inter",
          fontSize: 32,
          fill: GOLD,
        }),
      ]),
    ],
  },
  {
    id: "ink-square",
    name: "Ink square",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page(PAPER, [
        shape({ shape: "ellipse", x: 720, y: -80, width: 520, height: 520, fill: OXBLOOD }),
        text({
          x: 80,
          y: 360,
          width: 900,
          text: "Pressed,\nnot posted.",
          fontFamily: "Playfair Display",
          fontSize: 72,
          fontWeight: 600,
          fill: INK,
        }),
        text({
          x: 80,
          y: 900,
          width: 900,
          text: "IMPRINT  ·  A quiet mark",
          fontFamily: "Oswald",
          fontSize: 22,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
      ]),
    ],
  },
  {
    id: "studio-poster",
    name: "Studio poster",
    category: "print",
    width: 794,
    height: 1123,
    build: () => [
      page(PAPER, [
        shape({ shape: "rect", x: 0, y: 0, width: 794, height: 220, fill: INK }),
        text({
          x: 56,
          y: 70,
          width: 680,
          text: "OPEN STUDIO",
          fontFamily: "Oswald",
          fontSize: 56,
          fontWeight: 600,
          fill: PAPER,
        }),
        text({
          x: 56,
          y: 300,
          width: 680,
          text: "Paper, type, and the work of making a mark that lasts the week.",
          fontFamily: "Playfair Display",
          fontSize: 36,
          fontWeight: 500,
          fill: INK,
        }),
        shape({ shape: "rect", x: 56, y: 520, width: 80, height: 8, fill: OXBLOOD }),
        text({
          x: 56,
          y: 560,
          width: 680,
          text: "Saturday 11–4\nHarbor & Vine\nBring a pencil.",
          fontFamily: "Inter",
          fontSize: 24,
          fill: "#3f3833",
        }),
        text({
          x: 56,
          y: 1000,
          width: 680,
          text: "IMPRINT",
          fontFamily: "Oswald",
          fontSize: 20,
          fontWeight: 500,
          fill: OXBLOOD,
        }),
      ]),
    ],
  },
  {
    id: "quiet-invite",
    name: "Quiet invite",
    category: "print",
    width: 816,
    height: 1056,
    build: () => [
      page(CREAM, [
        shape({ shape: "rect", x: 48, y: 48, width: 720, height: 960, fill: "transparent", stroke: INK, strokeWidth: 2 }),
        text({
          x: 88,
          y: 280,
          width: 640,
          text: "You’re invited",
          fontFamily: "Playfair Display",
          fontSize: 52,
          fontWeight: 600,
          align: "center",
          fill: INK,
        }),
        text({
          x: 88,
          y: 380,
          width: 640,
          text: "An evening of paper and conversation.",
          fontFamily: "Inter",
          fontSize: 22,
          align: "center",
          fill: "#3f3833",
        }),
        shape({ shape: "rect", x: 358, y: 460, width: 100, height: 4, fill: GOLD }),
        text({
          x: 88,
          y: 520,
          width: 640,
          text: "Friday, June 12 · 7pm\nThe upstairs room",
          fontFamily: "Inter",
          fontSize: 22,
          align: "center",
          fill: INK,
        }),
      ]),
    ],
  },
];

export function templateById(id: string): TemplateDef | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function templateThumbColors(id: string): { bg: string; accent: string } {
  const map: Record<string, { bg: string; accent: string }> = {
    "midnight-quote": { bg: INK, accent: GOLD },
    "launch-story": { bg: OXBLOOD, accent: PAPER },
    "thumbnail-hook": { bg: NAVY, accent: GOLD },
    "event-banner": { bg: FOREST, accent: CREAM },
    "brief-announcement": { bg: INK, accent: OXBLOOD },
    "keynote-title": { bg: NAVY, accent: GOLD },
    "keynote-deck": { bg: NAVY, accent: PAPER },
    "market-day": { bg: TERRACOTTA, accent: PAPER },
    "workshop-poster": { bg: PAPER, accent: INK },
    "letter-flyer": { bg: PAPER, accent: OXBLOOD },
    "band-tee": { bg: INK, accent: PAPER },
    "studio-mark": { bg: CREAM, accent: INK },
    "session-cover": { bg: FOREST, accent: GOLD },
    "menu-story": { bg: CREAM, accent: OXBLOOD },
    "case-study": { bg: INK, accent: GOLD },
    "simple-site": { bg: CREAM, accent: OXBLOOD },
    "wide-landing": { bg: NAVY, accent: GOLD },
    "studio-note": { bg: CREAM, accent: OXBLOOD },
    "saturday-hours": { bg: PAPER, accent: OXBLOOD },
    "paper-talk": { bg: PAPER, accent: OXBLOOD },
    "ink-square": { bg: PAPER, accent: INK },
    "studio-poster": { bg: PAPER, accent: INK },
    "quiet-invite": { bg: CREAM, accent: GOLD },
  };
  return map[id] ?? { bg: PAPER, accent: INK };
}

