import type { ButtonObject, Page, ShapeObject, TemplateDef, TextObject } from "../types";
import { uuid } from "../lib/ids";

export type ShowcaseWork = TemplateDef & {
  client: string;
  trade: string;
};

function text(
  partial: Pick<TextObject, "x" | "y" | "width" | "text"> & Partial<Omit<TextObject, "id" | "type">>,
): TextObject {
  return {
    id: uuid(),
    type: "text",
    x: partial.x,
    y: partial.y,
    width: partial.width,
    text: partial.text,
    rotation: partial.rotation ?? 0,
    opacity: partial.opacity ?? 1,
    fontWeight: partial.fontWeight ?? 400,
    fontFamily: partial.fontFamily ?? "Inter",
    align: partial.align ?? "left",
    fill: partial.fill ?? "#1a1614",
    fontSize: partial.fontSize ?? 24,
  };
}

function shape(
  partial: Omit<ShapeObject, "id" | "type" | "rotation" | "opacity" | "stroke" | "strokeWidth" | "cornerRadius"> &
    Partial<ShapeObject>,
): ShapeObject {
  return {
    id: uuid(),
    type: "shape",
    rotation: 0,
    opacity: 1,
    stroke: "transparent",
    strokeWidth: 0,
    cornerRadius: 0,
    ...partial,
  };
}

function button(
  partial: Pick<ButtonObject, "x" | "y" | "width" | "height" | "text" | "href"> & Partial<ButtonObject>,
): ButtonObject {
  return {
    id: uuid(),
    type: "button",
    rotation: 0,
    opacity: 1,
    fill: "#0f2744",
    textFill: "#f6f1e8",
    fontFamily: "Inter",
    fontSize: 22,
    fontWeight: 600,
    cornerRadius: 8,
    ...partial,
  };
}

function page(background: Page["background"], objects: Page["objects"]): Page {
  return { id: uuid(), background, objects };
}

export const SHOWCASE: ShowcaseWork[] = [
  {
    id: "work-north-rye",
    name: "Friday loaf",
    client: "North & Rye",
    trade: "Bakery",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page("#f3e4c8", [
        shape({ shape: "rect", x: 0, y: 0, width: 1080, height: 1080, fill: "#f3e4c8" }),
        shape({ shape: "rect", x: 0, y: 0, width: 1080, height: 96, fill: "#5c3317" }),
        shape({ shape: "ellipse", x: 78, y: 160, width: 132, height: 132, fill: "#5c3317" }),
        text({
          x: 78,
          y: 198,
          width: 132,
          text: "N&R",
          fontFamily: "Fraunces",
          fontSize: 28,
          fontWeight: 600,
          align: "center",
          fill: "#f3e4c8",
        }),
        text({
          x: 78,
          y: 28,
          width: 920,
          text: "NORTH & RYE  ·  HARBOR STREET",
          fontFamily: "Outfit",
          fontSize: 22,
          fontWeight: 500,
          fill: "#f3e4c8",
        }),
        text({
          x: 78,
          y: 340,
          width: 920,
          text: "Friday\nloaf.",
          fontFamily: "Fraunces",
          fontSize: 118,
          fontWeight: 600,
          fill: "#5c3317",
        }),
        text({
          x: 78,
          y: 640,
          width: 700,
          text: "Walnut levain. Still warm at 6.",
          fontFamily: "Outfit",
          fontSize: 36,
          fontWeight: 400,
          fill: "#8a5a32",
        }),
        shape({ shape: "rect", x: 78, y: 860, width: 220, height: 88, fill: "#5c3317", cornerRadius: 8 }),
        text({
          x: 78,
          y: 882,
          width: 220,
          text: "$8",
          fontFamily: "Outfit",
          fontSize: 36,
          fontWeight: 600,
          align: "center",
          fill: "#f3e4c8",
        }),
        text({
          x: 330,
          y: 886,
          width: 640,
          text: "Slice at the counter. Loaves till noon.",
          fontFamily: "Outfit",
          fontSize: 24,
          fontWeight: 400,
          fill: "#5c3317",
        }),
      ]),
    ],
  },
  {
    id: "work-solace",
    name: "New patient Friday",
    client: "Solace Dental",
    trade: "Clinic",
    category: "social",
    width: 1080,
    height: 1920,
    build: () => [
      page("#eaf4f1", [
        shape({ shape: "rect", x: 0, y: 0, width: 1080, height: 720, fill: "#1f5c57", cornerRadius: 0 }),
        shape({ shape: "ellipse", x: 780, y: -80, width: 420, height: 420, fill: "#2a736c" }),
        text({
          x: 72,
          y: 80,
          width: 800,
          text: "SOLACE",
          fontFamily: "Manrope",
          fontSize: 28,
          fontWeight: 600,
          fill: "#d7efe8",
        }),
        text({
          x: 72,
          y: 280,
          width: 880,
          text: "A quieter\ndental visit.",
          fontFamily: "Fraunces",
          fontSize: 78,
          fontWeight: 500,
          fill: "#f4fffb",
        }),
        text({
          x: 72,
          y: 820,
          width: 900,
          text: "New patient Friday",
          fontFamily: "Manrope",
          fontSize: 42,
          fontWeight: 600,
          fill: "#1f5c57",
        }),
        shape({ shape: "rect", x: 72, y: 920, width: 936, height: 120, fill: "#ffffff", cornerRadius: 16 }),
        text({
          x: 100,
          y: 954,
          width: 880,
          text: "Cleaning  ·  9:40am  ·  Dr. Patel",
          fontFamily: "Manrope",
          fontSize: 32,
          fontWeight: 500,
          fill: "#1f5c57",
        }),
        shape({ shape: "rect", x: 72, y: 1068, width: 936, height: 120, fill: "#ffffff", cornerRadius: 16 }),
        text({
          x: 100,
          y: 1102,
          width: 880,
          text: "Consult  ·  11:15am  ·  still open",
          fontFamily: "Manrope",
          fontSize: 32,
          fontWeight: 500,
          fill: "#1f5c57",
        }),
        shape({ shape: "rect", x: 72, y: 1640, width: 936, height: 120, fill: "#1f5c57", cornerRadius: 60 }),
        text({
          x: 72,
          y: 1674,
          width: 936,
          text: "Book at solace.care",
          fontFamily: "Manrope",
          fontSize: 32,
          fontWeight: 600,
          align: "center",
          fill: "#f4fffb",
        }),
      ]),
    ],
  },
  {
    id: "work-mira",
    name: "Look 08",
    client: "Mira Atelier",
    trade: "Fashion",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page("#161114", [
        shape({ shape: "rect", x: 0, y: 0, width: 1080, height: 1080, fill: "#161114" }),
        shape({ shape: "rect", x: 0, y: 0, width: 18, height: 1080, fill: "#e8b4b8" }),
        text({
          x: 80,
          y: 64,
          width: 900,
          text: "MIRA ATELIER",
          fontFamily: "Syne",
          fontSize: 22,
          fontWeight: 600,
          fill: "#e8b4b8",
        }),
        text({
          x: 80,
          y: 280,
          width: 920,
          text: "LOOK\n08",
          fontFamily: "Syne",
          fontSize: 160,
          fontWeight: 700,
          fill: "#f7ecec",
        }),
        text({
          x: 80,
          y: 720,
          width: 800,
          text: "Wool coat. Blush lining.\nFall drop, one night only.",
          fontFamily: "Instrument Serif",
          fontSize: 36,
          fontWeight: 400,
          fill: "#e8b4b8",
        }),
        text({
          x: 80,
          y: 960,
          width: 900,
          text: "Oak & Pine  ·  Thursday 7pm",
          fontFamily: "Syne",
          fontSize: 22,
          fontWeight: 500,
          fill: "#9a7a7e",
        }),
      ]),
    ],
  },
  {
    id: "work-cedar-salt",
    name: "Tonight's board",
    client: "Cedar & Salt",
    trade: "Restaurant",
    category: "print",
    width: 794,
    height: 1123,
    build: () => [
      page("#24362c", [
        shape({ shape: "rect", x: 48, y: 48, width: 698, height: 1027, fill: "#f6f0e4" }),
        text({
          x: 90,
          y: 88,
          width: 610,
          text: "CEDAR & SALT",
          fontFamily: "Cormorant Garamond",
          fontSize: 28,
          fontWeight: 600,
          align: "center",
          fill: "#24362c",
        }),
        text({
          x: 90,
          y: 160,
          width: 610,
          text: "Tonight’s board",
          fontFamily: "Cormorant Garamond",
          fontSize: 56,
          fontWeight: 500,
          align: "center",
          fill: "#24362c",
        }),
        shape({ shape: "line", x: 220, y: 250, width: 350, height: 3, fill: "#24362c" }),
        text({
          x: 110,
          y: 300,
          width: 574,
          text: "Oysters  ·  mignonette\nCelery root  ·  brown butter\nMackerel  ·  grilled lemon\nTart  ·  rye & cream",
          fontFamily: "Newsreader",
          fontSize: 32,
          fontWeight: 400,
          align: "center",
          fill: "#24362c",
        }),
        text({
          x: 110,
          y: 720,
          width: 574,
          text: "Seatings at 6 and 8.\nWalk-ins at the bar.",
          fontFamily: "Karla",
          fontSize: 22,
          fontWeight: 400,
          align: "center",
          fill: "#4a6354",
        }),
        text({
          x: 110,
          y: 960,
          width: 574,
          text: "Harbor Lane  ·  Thursday",
          fontFamily: "Karla",
          fontSize: 18,
          fontWeight: 500,
          align: "center",
          fill: "#24362c",
        }),
      ]),
    ],
  },
  {
    id: "work-hale",
    name: "Q3 counsel",
    client: "Hale & Co.",
    trade: "Law",
    category: "presentation",
    width: 1920,
    height: 1080,
    build: () => [
      page("#0f2744", [
        shape({ shape: "rect", x: 0, y: 0, width: 18, height: 1080, fill: "#c9a227" }),
        text({
          x: 96,
          y: 72,
          width: 800,
          text: "HALE & CO.  ·  ATTORNEYS",
          fontFamily: "IBM Plex Sans",
          fontSize: 22,
          fontWeight: 500,
          fill: "#c9a227",
        }),
        text({
          x: 96,
          y: 280,
          width: 1400,
          text: "Counsel for\nthe third quarter.",
          fontFamily: "IBM Plex Sans",
          fontSize: 78,
          fontWeight: 600,
          fill: "#f4f6f8",
        }),
        text({
          x: 96,
          y: 560,
          width: 1100,
          text: "A short briefing for the board. Contracts, risk, and what we are not doing.",
          fontFamily: "IBM Plex Sans",
          fontSize: 28,
          fontWeight: 400,
          fill: "#b7c4d4",
        }),
        text({
          x: 96,
          y: 940,
          width: 900,
          text: "September  ·  Confidential",
          fontFamily: "IBM Plex Sans",
          fontSize: 20,
          fontWeight: 500,
          fill: "#c9a227",
        }),
      ]),
    ],
  },
  {
    id: "work-bloomroom",
    name: "Peonies this week",
    client: "Bloomroom",
    trade: "Florist",
    category: "social",
    width: 1080,
    height: 1920,
    build: () => [
      page("#f3e6ea", [
        shape({ shape: "ellipse", x: -120, y: -80, width: 520, height: 520, fill: "#e4c4cc" }),
        shape({ shape: "ellipse", x: 700, y: 1480, width: 480, height: 480, fill: "#d7e3d0" }),
        text({
          x: 80,
          y: 120,
          width: 900,
          text: "Bloomroom",
          fontFamily: "Great Vibes",
          fontSize: 72,
          fontWeight: 400,
          fill: "#6b3a44",
        }),
        text({
          x: 80,
          y: 620,
          width: 900,
          text: "Peonies\nthis week.",
          fontFamily: "Figtree",
          fontSize: 92,
          fontWeight: 600,
          fill: "#3d2a2e",
        }),
        text({
          x: 80,
          y: 980,
          width: 880,
          text: "Blush, coral, and a few that still smell like the greenhouse.",
          fontFamily: "Figtree",
          fontSize: 32,
          fontWeight: 400,
          fill: "#6b3a44",
        }),
        shape({ shape: "rect", x: 80, y: 1600, width: 920, height: 100, fill: "#6b3a44", cornerRadius: 50 }),
        text({
          x: 80,
          y: 1628,
          width: 920,
          text: "Order a bunch  ·  Vine Street",
          fontFamily: "Figtree",
          fontSize: 28,
          fontWeight: 600,
          align: "center",
          fill: "#f3e6ea",
        }),
      ]),
    ],
  },
  {
    id: "work-volt",
    name: "Open 5am",
    client: "Volt Coffee",
    trade: "Cafe",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page("#111111", [
        shape({ shape: "rect", x: 64, y: 64, width: 952, height: 952, fill: "#111111", stroke: "#f4d35e", strokeWidth: 8 }),
        text({
          x: 100,
          y: 140,
          width: 880,
          text: "VOLT",
          fontFamily: "Anton",
          fontSize: 48,
          fontWeight: 400,
          fill: "#f4d35e",
        }),
        text({
          x: 90,
          y: 320,
          width: 900,
          text: "OPEN\n5AM",
          fontFamily: "Anton",
          fontSize: 180,
          fontWeight: 400,
          fill: "#f7f4ea",
        }),
        text({
          x: 100,
          y: 860,
          width: 880,
          text: "Oat, batch, no line if you know the alley door.",
          fontFamily: "Space Grotesk",
          fontSize: 26,
          fontWeight: 500,
          fill: "#f4d35e",
        }),
      ]),
    ],
  },
  {
    id: "work-pebble",
    name: "After school",
    client: "Pebble",
    trade: "Kids",
    category: "social",
    width: 1080,
    height: 1080,
    build: () => [
      page("#fff4dc", [
        shape({ shape: "ellipse", x: 760, y: -80, width: 420, height: 420, fill: "#8ec5ff" }),
        shape({ shape: "ellipse", x: -80, y: 780, width: 340, height: 340, fill: "#ffb4a2" }),
        shape({ shape: "rect", x: 90, y: 90, width: 900, height: 900, fill: "#ffffff", cornerRadius: 48 }),
        text({
          x: 140,
          y: 160,
          width: 800,
          text: "pebble",
          fontFamily: "Nunito",
          fontSize: 32,
          fontWeight: 700,
          fill: "#3d6fd8",
        }),
        text({
          x: 140,
          y: 320,
          width: 800,
          text: "After school\nuntil 6.",
          fontFamily: "Nunito",
          fontSize: 72,
          fontWeight: 700,
          fill: "#1e2a44",
        }),
        text({
          x: 140,
          y: 580,
          width: 780,
          text: "Snacks, homework, and a yard that still has chalk on it.",
          fontFamily: "Nunito",
          fontSize: 30,
          fontWeight: 500,
          fill: "#4a5870",
        }),
        shape({ shape: "rect", x: 140, y: 780, width: 360, height: 88, fill: "#3d6fd8", cornerRadius: 44 }),
        text({
          x: 140,
          y: 802,
          width: 360,
          text: "Hold a spot",
          fontFamily: "Nunito",
          fontSize: 26,
          fontWeight: 700,
          align: "center",
          fill: "#ffffff",
        }),
      ]),
    ],
  },
  {
    id: "work-aero",
    name: "Freight that shows up",
    client: "Aero Route",
    trade: "Logistics",
    category: "site",
    width: 1440,
    height: 900,
    build: () => [
      page("#071018", [
        shape({ shape: "rect", x: 0, y: 0, width: 1440, height: 72, fill: "#0c1a24" }),
        text({
          x: 48,
          y: 22,
          width: 400,
          text: "AERO ROUTE",
          fontFamily: "Space Grotesk",
          fontSize: 22,
          fontWeight: 600,
          fill: "#3dd6c6",
        }),
        text({
          x: 900,
          y: 24,
          width: 500,
          text: "Track  ·  Lanes  ·  Contact",
          fontFamily: "Space Grotesk",
          fontSize: 16,
          fontWeight: 500,
          align: "right",
          fill: "#9ab0b8",
        }),
        text({
          x: 72,
          y: 220,
          width: 1000,
          text: "Freight that\nshows up.",
          fontFamily: "Space Grotesk",
          fontSize: 88,
          fontWeight: 600,
          fill: "#eef7f6",
        }),
        text({
          x: 72,
          y: 460,
          width: 720,
          text: "Lanes from the port to the floor. Live ETAs, not a spreadsheet from Tuesday.",
          fontFamily: "IBM Plex Sans",
          fontSize: 24,
          fontWeight: 400,
          fill: "#9ab0b8",
        }),
        button({
          x: 72,
          y: 600,
          width: 220,
          height: 56,
          text: "Get a lane",
          href: "https://example.com",
          fill: "#3dd6c6",
          textFill: "#071018",
          fontFamily: "Space Grotesk",
          fontSize: 18,
          cornerRadius: 6,
        }),
        shape({ shape: "rect", x: 980, y: 180, width: 380, height: 540, fill: "#0c1a24", cornerRadius: 16 }),
        text({
          x: 1010,
          y: 220,
          width: 320,
          text: "LANE 14\nOn time\n\nChicago → Austin\n2h 14m",
          fontFamily: "JetBrains Mono",
          fontSize: 22,
          fontWeight: 500,
          fill: "#3dd6c6",
        }),
      ]),
    ],
  },
  {
    id: "work-kin",
    name: "Saturday flow",
    client: "Kin Yoga",
    trade: "Studio",
    category: "print",
    width: 794,
    height: 1123,
    build: () => [
      page("#f4eee4", [
        shape({ shape: "ellipse", x: 220, y: 80, width: 360, height: 360, fill: "#d9c7e6" }),
        text({
          x: 70,
          y: 480,
          width: 654,
          text: "KIN",
          fontFamily: "Unbounded",
          fontSize: 92,
          fontWeight: 600,
          align: "center",
          fill: "#3b2d4a",
        }),
        text({
          x: 70,
          y: 600,
          width: 654,
          text: "Saturday flow",
          fontFamily: "Instrument Serif",
          fontSize: 42,
          fontWeight: 400,
          align: "center",
          fill: "#3b2d4a",
        }),
        text({
          x: 90,
          y: 720,
          width: 614,
          text: "10:00–11:15  ·  All levels\nMats at the door. Tea after.",
          fontFamily: "Figtree",
          fontSize: 24,
          fontWeight: 400,
          align: "center",
          fill: "#5c4d6a",
        }),
        text({
          x: 90,
          y: 980,
          width: 614,
          text: "The upstairs room  ·  Elm",
          fontFamily: "Figtree",
          fontSize: 18,
          fontWeight: 500,
          align: "center",
          fill: "#3b2d4a",
        }),
      ]),
    ],
  },
  {
    id: "work-orchard",
    name: "Thursday checkup",
    client: "Orchard Vet",
    trade: "Clinic",
    category: "email",
    width: 600,
    height: 800,
    build: () => [
      page("#f7f3ea", [
        shape({ shape: "rect", x: 0, y: 0, width: 600, height: 88, fill: "#3d5c3a" }),
        text({
          x: 28,
          y: 30,
          width: 540,
          text: "ORCHARD VET",
          fontFamily: "Plus Jakarta Sans",
          fontSize: 18,
          fontWeight: 700,
          fill: "#f7f3ea",
        }),
        text({
          x: 36,
          y: 140,
          width: 528,
          text: "Juniper’s checkup is Thursday.",
          fontFamily: "Fraunces",
          fontSize: 36,
          fontWeight: 500,
          fill: "#2a3d28",
        }),
        text({
          x: 36,
          y: 280,
          width: 528,
          text: "Dr. Ellis  ·  2:20pm\nBring the little blue leash if you still have it.",
          fontFamily: "Plus Jakarta Sans",
          fontSize: 20,
          fontWeight: 400,
          fill: "#3d5c3a",
        }),
        button({
          x: 36,
          y: 480,
          width: 220,
          height: 52,
          text: "Add to calendar",
          href: "https://example.com",
          fill: "#3d5c3a",
          textFill: "#f7f3ea",
          fontFamily: "Plus Jakarta Sans",
          fontSize: 16,
          cornerRadius: 8,
        }),
        text({
          x: 36,
          y: 720,
          width: 528,
          text: "Orchard Vet  ·  Maple Court",
          fontFamily: "Plus Jakarta Sans",
          fontSize: 14,
          fontWeight: 500,
          fill: "#6b7d68",
        }),
      ]),
    ],
  },
];

